#!/bin/sh
set -e

case "$1" in
  remove|upgrade|deconfigure)
    # Only remove diversion if it exists
     dpkg-divert --package kainat-os-sources --remove --rename \
        --divert /etc/apt/sources.list.divert /etc/apt/sources.list
  *)
    # No action needed for other prerm states
    ;;
esac

exit 0
