#!/bin/bash
set -e

# File: debian/postinst
# Purpose: Post-install script for nvidia-driver-kainatos
# This will update all initramfs images so the new NVIDIA modules are included.

case "$1" in
  configure)
      update-initramfs -u -k all
    ;;
esac

exit 0
