#!/bin/sh
set -e

# This script is run by dpkg after package installation/configuration.

case "$1" in
  configure)
    # only try to use systemd if it's available
    chmod 777 -R /opt/chat-sotero
    ;;
esac

exit 0
